server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    port: 8080
    type: http
  rootPath: /*

oracleSqlConfig:
  driver: "oracle.jdbc.driver.OracleDriver"
  url: "jdbc:oracle:thin:@Sumit11:1521:xe"
  username: "System"
  password: "tiger"