spring.application.name=company-portal

spring.datasource.url=jdbc:postgresql://localhost:5432/AryabhataTechDB
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.root=INFO

# Log file location
logging.file.name=A:/workspace/logs/company-portal/application.log

# Rolling Policy
logging.logback.rollingpolicy.file-name-pattern=A:/workspace/logs/company-portal/application-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5