spring:
  application:
    name: "hello-world-spring"


#  config:
#    import: "classpath:emailConfig.yml"

## this log properties not work, because here logback.xml template is available.
#logging:
#  level:
#    root: INFO
#    com.project: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %logger{15} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %logger{15} - %msg%n"
#  file:
#    name: A:/workspace/logs/java-HelloSpring/application.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: A:/workspace/logs/java-HelloSpring/application-%d{yyyy-MM-dd}.log
#      max-history: 5


dataBase:
  driver: "com.mysql.cj.jdbc.Driver123456   (read through .yml file)"