spring.application.name=hello-world-spring
app.userMessage=Hello, Spring Boot World!! (read through application.properties)
database.url=jdbc:mysql://localhost:3306/banking_app (read through application.properties)
