app:
  userMessage: "Hello, Spring Boot World!"

logging:
  level:
    root: INFO
    com.project: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %logger{15} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{X-Session-Id} - %X{X-Request-Id}] - %logger{15} - %msg%n"
  file:
    name: C:/log/java-HelloSpring/application.log
  logback:
    rollingpolicy:
      file-name-pattern: C:/log/java-HelloSpring/application-%d{yyyy-MM-dd}.log
      max-history: 5


server:
  port: 8080

dataBase:
  driver: "com.mysql.cj.jdbc.Driver"